name: timeup
description: Um app de tempo extremamente elegante e bonito com animações fluidas e com tema de liquidglass
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  http: 1.2.0
  provider: 6.1.1
  shared_preferences: 2.2.2
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  dio: 5.4.0
  retrofit: 4.0.3
  json_annotation: 4.8.1
  freezed_annotation: 2.4.1
  get_it: 7.6.7
  injectable: 2.3.2
  go_router: 13.0.1
  flutter_screenutil: 5.9.0
  flutter_svg: 2.0.9
  cached_network_image: 3.3.1
  shimmer: 3.0.0
  pull_to_refresh: 2.0.0
  url_launcher: 6.2.4
  package_info_plus: 5.0.1
  device_info_plus: 9.1.2
  permission_handler: 11.2.0
  image_picker: 1.0.7
  file_picker: 6.1.1
  path_provider: 2.1.2
  open_filex: 4.3.4
  share_plus: 7.2.2
  connectivity_plus: 5.0.2
  webview_flutter: 4.5.0
  video_player: 2.8.2
  chewie: 1.7.4
  wakelock_plus: 1.1.4
  flutter_local_notifications: 16.3.2
  timezone: 0.9.2
  flutter_native_timezone: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  build_runner: 2.4.8
  retrofit_generator: 8.0.6
  json_serializable: 6.7.1
  freezed: 2.4.7
  injectable_generator: 2.4.1
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.10
  change_app_package_name: 1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/config/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
